### ISSUE TITLE
Not an issue - feature request - font layout of site title

### ISSUE THREAD

**Issue by Unblack** [pmoreno-rodriguez/grav-theme-delivernext#2]
It would be great if the font size an style of the title were selectable.

**Comment by pmoreno-rodriguez** [comment]
@Unblack , What do you mean by style? Font weight, italic, bold, etc., or font-family?
Perhaps some of these characteristics are easier to establish than others. I'll look into that.

**Comment by Unblack** [comment]
Yes, that's exactly what I meant. This makes it easier for site administrators who are not devops, like me

**Comment by 01Kuzma** [comment]
I want to report an issue regarding font styles, regarding characters, such as "ė,j,ų"
They are not rendered properly, maybe "latin-ext" is missing:

![Image](https://github.com/user-attachments/assets/78c46870-9dc7-40b0-a1da-ff724ba88f6b)

**Comment by oldstar84** [comment]
I got the same problem, with characters, like: "Ä,Ö,Ü" 

regards

**Comment by pmoreno-rodriguez** [comment]
Fixed in version 2.1.2. Please test it and confirm that the issue is working correctly.

**Comment by oldstar84** [comment]
It seems it is still the same after updating:

`## Gebührenordnung` is displayed as:
<img width="258" height="48" alt="Image" src="https://github.com/user-attachments/assets/cc2043e9-566f-47af-8ada-42725ae235a2" />

regards

**Comment by pmoreno-rodriguez** [comment]
> It seems it is still the same after updating:
> 
> `## Gebührenordnung` is displayed as: <img alt="Image" width="258" height="48" src="https://private-user-images.githubusercontent.com/158184781/620401984-cc2043e9-566f-47af-8ada-42725ae235a2.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODM3NjQ0ODQsIm5iZiI6MTc4Mzc2NDE4NCwicGF0aCI6Ii8xNTgxODQ3ODEvNjIwNDAxOTg0LWNjMjA0M2U5LTU2NmYtNDdhZi04YWRhLTQyNzI1YWUyMzVhMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwNzExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDcxMVQxMDAzMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZDJlY2MyNDk2MTgyMGQ5ZDc4NTIwNWRmMjZiZGQ1MzVlNThmYTM5NGRjYTc5NmI4ZjhkOTQ2ZjBlNTI0NDJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZyZXNwb25zZS1jb250ZW50LXR5cGU9aW1hZ2UlMkZwbmcifQ.94jXhEncOItEAJPpnulsqQo8KNX13x77WRfPt7VaSU8">
> 
> regards


I don't see any difference between the markdown and the final result shown on the page

**Comment by oldstar84** [comment]
"ü" is not as bold as the other characters

**Comment by oldstar84** [comment]
It seems, that font-family novecento_sans_widedemibold doesn't include "bold-looking" charachters of ä.ö,ü
So, the original author of this issue was asking, if the font could be select able. This will fix it.

Or does a custom .css overrides the original .css? I think it does not.
